apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: pod
  labels:
    app.kubernetes.io/name: test-svc
    app.kubernetes.io/version: v1
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kubectl
spec:
  containers:
    - name: app
      image: mogumogusityau/service:v1.0.0
      ports:
        - containerPort: 3000
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MODE
          value: "web"
        - name: APP_VERSION
          value: "v1"
        - name: DATA_DIR
          value: "/data"
      volumeMounts:
        - name: data
          mountPath: /data
      readinessProbe:
        httpGet:
          path: /readyz
          port: 3000
        initialDelaySeconds: 1
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
  volumes:
    - name: data
      emptyDir: {} 