apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - name: http
      port: 80 
      targetPort: 3000
      nodePort: 30080
