apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: test-svc
  labels:
    app.kubernetes.io/name: test-svc
    app.kubernetes.io/version: v1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: test-svc
  ports:
    - name: http
      port: 3000
      targetPort: 3000