apiVersion: v1
kind: Pod
metadata:
  name: service1
  labels:
    app.kubernetes.io/name: service1
spec:
  containers:
    - name: app
      image: mogumogusityau/service1:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service1-config
              key: PORT